### ISSUE TITLE
PDF turns blank when uploaded to GitHub

### ISSUE THREAD

**Issue by jefitzge** [jefitzge/jefitzge.github.io#10]
When uploading my personal file FitzgeraldJosephResume_v1.pdf, which has data, it is shown to be blank. Viewing the file on GitHub shows it as a blank file but the proper file size.
Not sure what the issue is but using the inspect element feature in chrome I saw the following:

Error: Invalid XRef stream header
pdf.worker-64541af1ea338bd40b1739975dd42a1e.js:1     at n (https://render.githubusercontent.com/assets/pdf.worker-64541af1ea338bd40b1739975dd42a1e.js:1:39981)
    at e.readXRef (https://render.githubusercontent.com/assets/pdf.worker-64541af1ea338bd40b1739975dd42a1e.js:1:487345)
    at e.indexObjects (https://render.githubusercontent.com/assets/pdf.worker-64541af1ea338bd40b1739975dd42a1e.js:1:486468)
    at e.parse (https://render.githubusercontent.com/assets/pdf.worker-64541af1ea338bd40b1739975dd42a1e.js:1:482706)
    at e.setup (https://render.githubusercontent.com/assets/pdf.worker-64541af1ea338bd40b1739975dd42a1e.js:1:559696)
    at e.parse (https://render.githubusercontent.com/assets/pdf.worker-64541af1ea338bd40b1739975dd42a1e.js:1:558320)
    at https://render.githubusercontent.com/assets/pdf.worker-64541af1ea338bd40b1739975dd42a1e.js:1:562511
    at new Promise (<anonymous>)
    at ensure (https://render.githubusercontent.com/assets/pdf.worker-64541af1ea338bd40b1739975dd42a1e.js:1:562444)

**Comment by jefitzge** [comment]
The error seems to have been an issue with the file itself, not sure what, but it has been resolved by reuploading another version of the PDF.
